apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ghost-app-volume
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pv-claim
  labels:
    app: ghost
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ghost-app-volume
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:latest
          ports:
            - containerPort: 2368
        env:
          - name: database__client
            value: mysql
          - name: database__connection__host
              valueFrom:
              secretKeyRef:  # changed
              name: ghost-app-secret
              key: db_host
        - name: database__connection__port
          valueFrom:
            secretKeyRef:
              name: ghost-app-secret
              key: db_port
        - name: database__connection__user
          valueFrom:
            secretKeyRef:
              name: ghost-app-secret
              key: db_user
        - name: database__connection__password
          valueFrom:
            secretKeyRef:
              name: ghost-app-secret
              key: user_password
        - name: database__connection__database
          value: ghost_db  # your database name
        - name: mail__transport
          value: SMTP
        - name: mail__options__service
          value: Gmail  # your SMTP service
        - name: mail__options__auth__user
          valueFrom:
            secretKeyRef:
              name: ghost-app-secret
              key: smtp_username
        - name: mail__options__auth__pass
          valueFrom:
            secretKeyRef:
              name: ghost-app-secret
              key: smtp_password
        - name: mail__from
          valueFrom:
            secretKeyRef:
              name: ghost-app-secret
              key: mail_from
---
apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  labels:
    app: ghost
spec:
  type: ClusterIP
  selector:
    app: ghost
    tier: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 2368
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: blog-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blog-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: awsblog.jonestecsolutions.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: ghost-service
            port:
              number: 80
  tls:
  - hosts: 
    - awsblog.jonestecsolutions.com
    secretName: blog-tls